export const assetRegistryAbi = [
    { inputs: [], stateMutability: 'nonpayable', type: 'constructor' },
    { inputs: [{ internalType: 'address', name: 'target', type: 'address' }], name: 'AddressEmptyCode', type: 'error' },
    { inputs: [], name: 'AssetAlreadyAdded', type: 'error' },
    { inputs: [], name: 'AssetNotAdded', type: 'error' },
    { inputs: [{ internalType: 'address', name: 'implementation', type: 'address' }], name: 'ERC1967InvalidImplementation', type: 'error' },
    { inputs: [], name: 'ERC1967NonPayable', type: 'error' },
    { inputs: [], name: 'FailedInnerCall', type: 'error' },
    { inputs: [], name: 'InvalidInitialization', type: 'error' },
    { inputs: [], name: 'InvalidZeroAddress', type: 'error' },
    { inputs: [], name: 'NotInitializing', type: 'error' },
    { inputs: [], name: 'UUPSUnauthorizedCallContext', type: 'error' },
    { inputs: [{ internalType: 'bytes32', name: 'slot', type: 'bytes32' }], name: 'UUPSUnsupportedProxiableUUID', type: 'error' },
    { inputs: [], name: 'VaultNotEmpty', type: 'error' },
    { inputs: [{ internalType: 'address', name: 'asset', type: 'address' }], name: 'VaultNotFound', type: 'error' },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'asset', type: 'address' },
            { indexed: true, internalType: 'address', name: 'vault', type: 'address' },
        ],
        name: 'AssetAdded',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'asset', type: 'address' },
            { indexed: true, internalType: 'address', name: 'vault', type: 'address' },
        ],
        name: 'AssetRemoved',
        type: 'event',
    },
    { anonymous: false, inputs: [{ indexed: false, internalType: 'uint64', name: 'version', type: 'uint64' }], name: 'Initialized', type: 'event' },
    { anonymous: false, inputs: [{ indexed: true, internalType: 'address', name: 'implementation', type: 'address' }], name: 'Upgraded', type: 'event' },
    { inputs: [], name: 'UPGRADE_INTERFACE_VERSION', outputs: [{ internalType: 'string', name: '', type: 'string' }], stateMutability: 'view', type: 'function' },
    { inputs: [{ internalType: 'address', name: 'vault', type: 'address' }], name: 'addAsset', outputs: [], stateMutability: 'nonpayable', type: 'function' },
    { inputs: [], name: 'getAssets', outputs: [{ internalType: 'address[]', name: '', type: 'address[]' }], stateMutability: 'view', type: 'function' },
    { inputs: [], name: 'getConfig', outputs: [{ internalType: 'address', name: '', type: 'address' }], stateMutability: 'view', type: 'function' },
    {
        inputs: [{ internalType: 'address', name: 'asset', type: 'address' }],
        name: 'getVault',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: 'asset', type: 'address' }],
        name: 'getVaultBalance',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: 'asset', type: 'address' }],
        name: 'getVaultDepositLimit',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: 'asset', type: 'address' }],
        name: 'hasAsset',
        outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
        stateMutability: 'view',
        type: 'function',
    },
    { inputs: [{ internalType: 'address', name: 'configAddr', type: 'address' }], name: 'initialize', outputs: [], stateMutability: 'nonpayable', type: 'function' },
    { inputs: [], name: 'proxiableUUID', outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }], stateMutability: 'view', type: 'function' },
    { inputs: [{ internalType: 'address', name: 'asset', type: 'address' }], name: 'removeAsset', outputs: [], stateMutability: 'nonpayable', type: 'function' },
    {
        inputs: [
            { internalType: 'address', name: 'newImplementation', type: 'address' },
            { internalType: 'bytes', name: 'data', type: 'bytes' },
        ],
        name: 'upgradeToAndCall',
        outputs: [],
        stateMutability: 'payable',
        type: 'function',
    },
    { inputs: [], name: 'version', outputs: [{ internalType: 'string', name: '', type: 'string' }], stateMutability: 'pure', type: 'function' },
];
