export const bridgeAbi = [
    'constructor(address[] hotAddresses, address[] coldAddresses, uint64[] powers, address usdcAddress, uint64 _disputePeriodSeconds, uint64 _blockDurationMillis, uint64 _lockerThreshold)',
    'event ChangedBlockDurationMillis(uint64 newBlockDurationMillis)',
    'event ChangedDisputePeriodSeconds(uint64 newDisputePeriodSeconds)',
    'event ChangedLockerThreshold(uint64 newLockerThreshold)',
    'event Deposit(address indexed user, uint64 usd)',
    'event FailedPermitDeposit(address user, uint64 usd, uint32 errorCode)',
    'event FailedWithdrawal(bytes32 message, uint32 errorCode)',
    'event FinalizedValidatorSetUpdate(uint64 epoch, bytes32 hotValidatorSetHash, bytes32 coldValidatorSetHash)',
    'event FinalizedWithdrawal(address indexed user, address destination, uint64 usd, uint64 nonce, bytes32 message)',
    'event InvalidatedWithdrawal(tuple(address user, address destination, uint64 usd, uint64 nonce, uint64 requestedTime, uint64 requestedBlockNumber, bytes32 message) withdrawal)',
    'event ModifiedFinalizer(address indexed finalizer, bool isFinalizer)',
    'event ModifiedLocker(address indexed locker, bool isLocker)',
    'event Paused(address account)',
    'event RequestedValidatorSetUpdate(uint64 epoch, bytes32 hotValidatorSetHash, bytes32 coldValidatorSetHash, uint64 updateTime)',
    'event RequestedWithdrawal(address indexed user, address destination, uint64 usd, uint64 nonce, bytes32 message, uint64 requestedTime)',
    'event Unpaused(address account)',
    'function batchedDepositWithPermit(tuple(address user, uint64 usd, uint64 deadline, tuple(uint256 r, uint256 s, uint8 v) signature)[] deposits)',
    'function batchedFinalizeWithdrawals(bytes32[] messages)',
    'function batchedRequestWithdrawals(tuple(address user, address destination, uint64 usd, uint64 nonce, tuple(uint256 r, uint256 s, uint8 v)[] signatures)[] withdrawalRequests, tuple(uint64 epoch, address[] validators, uint64[] powers) hotValidatorSet)',
    'function blockDurationMillis() view returns (uint64)',
    'function changeBlockDurationMillis(uint64 newBlockDurationMillis, uint64 nonce, tuple(uint64 epoch, address[] validators, uint64[] powers) activeColdValidatorSet, tuple(uint256 r, uint256 s, uint8 v)[] signatures)',
    'function changeDisputePeriodSeconds(uint64 newDisputePeriodSeconds, uint64 nonce, tuple(uint64 epoch, address[] validators, uint64[] powers) activeColdValidatorSet, tuple(uint256 r, uint256 s, uint8 v)[] signatures)',
    'function changeLockerThreshold(uint64 newLockerThreshold, uint64 nonce, tuple(uint64 epoch, address[] validators, uint64[] powers) activeColdValidatorSet, tuple(uint256 r, uint256 s, uint8 v)[] signatures)',
    'function coldValidatorSetHash() view returns (bytes32)',
    'function disputePeriodSeconds() view returns (uint64)',
    'function emergencyUnlock(tuple(uint64 epoch, address[] hotAddresses, address[] coldAddresses, uint64[] powers) newValidatorSet, tuple(uint64 epoch, address[] validators, uint64[] powers) activeColdValidatorSet, tuple(uint256 r, uint256 s, uint8 v)[] signatures, uint64 nonce)',
    'function epoch() view returns (uint64)',
    'function finalizeValidatorSetUpdate()',
    'function finalizedWithdrawals(bytes32) view returns (bool)',
    'function finalizers(address) view returns (bool)',
    'function getLockersVotingLock() view returns (address[])',
    'function hotValidatorSetHash() view returns (bytes32)',
    'function invalidateWithdrawals(bytes32[] messages, uint64 nonce, tuple(uint64 epoch, address[] validators, uint64[] powers) activeColdValidatorSet, tuple(uint256 r, uint256 s, uint8 v)[] signatures)',
    'function isVotingLock(address locker) view returns (bool)',
    'function lockerThreshold() view returns (uint64)',
    'function lockers(address) view returns (bool)',
    'function modifyFinalizer(address finalizer, bool _isFinalizer, uint64 nonce, tuple(uint64 epoch, address[] validators, uint64[] powers) activeValidatorSet, tuple(uint256 r, uint256 s, uint8 v)[] signatures)',
    'function modifyLocker(address locker, bool _isLocker, uint64 nonce, tuple(uint64 epoch, address[] validators, uint64[] powers) activeValidatorSet, tuple(uint256 r, uint256 s, uint8 v)[] signatures)',
    'function nValidators() view returns (uint64)',
    'function paused() view returns (bool)',
    'function pendingValidatorSetUpdate() view returns (uint64 epoch, uint64 totalValidatorPower, uint64 updateTime, uint64 updateBlockNumber, uint64 nValidators, bytes32 hotValidatorSetHash, bytes32 coldValidatorSetHash)',
    'function requestedWithdrawals(bytes32) view returns (address user, address destination, uint64 usd, uint64 nonce, uint64 requestedTime, uint64 requestedBlockNumber, bytes32 message)',
    'function totalValidatorPower() view returns (uint64)',
    'function unvoteEmergencyLock()',
    'function updateValidatorSet(tuple(uint64 epoch, address[] hotAddresses, address[] coldAddresses, uint64[] powers) newValidatorSet, tuple(uint64 epoch, address[] validators, uint64[] powers) activeHotValidatorSet, tuple(uint256 r, uint256 s, uint8 v)[] signatures)',
    'function usdcToken() view returns (address)',
    'function usedMessages(bytes32) view returns (bool)',
    'function voteEmergencyLock()',
    'function withdrawalsInvalidated(bytes32) view returns (bool)',
];
