export const bondingCurveAbi = [
    {
        inputs: [
            { internalType: 'address', name: '_factory', type: 'address' },
            { internalType: 'address', name: '_formula', type: 'address' },
            { internalType: 'uint32', name: '_weight', type: 'uint32' },
        ],
        stateMutability: 'nonpayable',
        type: 'constructor',
    },
    { inputs: [], name: 'FailedToSendETH', type: 'error' },
    { inputs: [], name: 'InvalidAmount', type: 'error' },
    { inputs: [], name: 'InvalidBalanceInvariant', type: 'error' },
    { inputs: [], name: 'InvalidCaller', type: 'error' },
    { inputs: [], name: 'InvalidToken', type: 'error' },
    { inputs: [{ internalType: 'uint256', name: 'maxFee', type: 'uint256' }], name: 'MaxFeeExceeded', type: 'error' },
    { inputs: [], name: 'ProtocolPaused', type: 'error' },
    { inputs: [], name: 'ReentrancyGuardReentrantCall', type: 'error' },
    { inputs: [], name: 'SlippageTooHigh', type: 'error' },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'user', type: 'address' },
            { indexed: true, internalType: 'address', name: 'token', type: 'address' },
            { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'amountOut', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'totalSupply', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'marketCap', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'price', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'reserveBalance', type: 'uint256' },
        ],
        name: 'Buy',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'token', type: 'address' },
            { indexed: true, internalType: 'address', name: 'pool', type: 'address' },
        ],
        name: 'LPSeeded',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'user', type: 'address' },
            { indexed: true, internalType: 'address', name: 'token', type: 'address' },
            { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'amountOut', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'totalSupply', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'marketCap', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'price', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'reserveBalance', type: 'uint256' },
        ],
        name: 'Sell',
        type: 'event',
    },
    { anonymous: false, inputs: [{ indexed: false, internalType: 'uint256', name: 'fee', type: 'uint256' }], name: 'TxFeeUpdated', type: 'event' },
    { inputs: [], name: 'MAX_FEE', outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
    {
        inputs: [
            { internalType: 'address', name: 'token', type: 'address' },
            { internalType: 'uint256', name: 'expectedOut', type: 'uint256' },
        ],
        name: 'buy',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'payable',
        type: 'function',
    },
    { inputs: [], name: 'factory', outputs: [{ internalType: 'contract GuFactory', name: '', type: 'address' }], stateMutability: 'view', type: 'function' },
    { inputs: [], name: 'formula', outputs: [{ internalType: 'address', name: '', type: 'address' }], stateMutability: 'view', type: 'function' },
    {
        inputs: [
            { internalType: 'address', name: 'token', type: 'address' },
            { internalType: 'uint256', name: 'amount', type: 'uint256' },
        ],
        name: 'getAmountOutBuy',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'token', type: 'address' },
            { internalType: 'uint256', name: 'amount', type: 'uint256' },
        ],
        name: 'getAmountOutBuySupplyCapped',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'token', type: 'address' },
            { internalType: 'uint256', name: 'amount', type: 'uint256' },
        ],
        name: 'getAmountOutSell',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    { inputs: [], name: 'reserveWeight', outputs: [{ internalType: 'uint32', name: '', type: 'uint32' }], stateMutability: 'view', type: 'function' },
    {
        inputs: [
            { internalType: 'address', name: 'token', type: 'address' },
            { internalType: 'uint256', name: 'amount', type: 'uint256' },
            { internalType: 'uint256', name: 'expectedOut', type: 'uint256' },
        ],
        name: 'sell',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    { inputs: [{ internalType: 'uint256', name: '_fee', type: 'uint256' }], name: 'setTxFee', outputs: [], stateMutability: 'nonpayable', type: 'function' },
    { inputs: [], name: 'txFee', outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
    { inputs: [{ internalType: 'uint256', name: 'amount', type: 'uint256' }], name: 'withdraw', outputs: [], stateMutability: 'nonpayable', type: 'function' },
    { stateMutability: 'payable', type: 'receive' },
];