export const factoryAbi = [
    {
        inputs: [
            { internalType: 'address', name: 'owner', type: 'address' },
            { internalType: 'address', name: '_harvester', type: 'address' },
            { internalType: 'address', name: 'layerZeroEndpoint', type: 'address' },
            { internalType: 'address', name: '_positionManager', type: 'address' },
            { internalType: 'address', name: '_weth', type: 'address' },
            { internalType: 'uint256', name: '_virtualReserves', type: 'uint256' },
            { internalType: 'uint256', name: '_initialSupply', type: 'uint256' },
            { internalType: 'uint256', name: '_maxSupply', type: 'uint256' },
            { internalType: 'uint80', name: '_protocolFee', type: 'uint80' },
            { internalType: 'uint80', name: '_creatorFee', type: 'uint80' },
            { internalType: 'uint80', name: '_creationFee', type: 'uint80' },
        ],
        stateMutability: 'nonpayable',
        type: 'constructor',
    },
    { inputs: [], name: 'BondingCurveNotSet', type: 'error' },
    { inputs: [], name: 'FailedToSendETH', type: 'error' },
    { inputs: [], name: 'InsufficientCreationFee', type: 'error' },
    { inputs: [], name: 'InvalidFees', type: 'error' },
    { inputs: [], name: 'InvalidInitialParams', type: 'error' },
    { inputs: [], name: 'InvalidParams', type: 'error' },
    { inputs: [], name: 'InvalidZeroAddress', type: 'error' },
    { inputs: [], name: 'LiquidityManagerNotSet', type: 'error' },
    { inputs: [{ internalType: 'address', name: 'owner', type: 'address' }], name: 'OwnableInvalidOwner', type: 'error' },
    { inputs: [{ internalType: 'address', name: 'account', type: 'address' }], name: 'OwnableUnauthorizedAccount', type: 'error' },
    { inputs: [], name: 'ProtocolPaused', type: 'error' },
    {
        anonymous: false,
        inputs: [
            { indexed: false, internalType: 'uint80', name: 'protocolFee', type: 'uint80' },
            { indexed: false, internalType: 'uint80', name: 'creatorFee', type: 'uint80' },
            { indexed: false, internalType: 'uint80', name: 'creationFee', type: 'uint80' },
        ],
        name: 'FeesUpdated',
        type: 'event',
    },
    { anonymous: false, inputs: [{ indexed: false, internalType: 'address', name: 'bondingCurve', type: 'address' }], name: 'GuBondingCurveUpdated', type: 'event' },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'creator', type: 'address' },
            { indexed: true, internalType: 'address', name: 'token', type: 'address' },
            { indexed: false, internalType: 'address', name: 'factory', type: 'address' },
            { indexed: false, internalType: 'address', name: 'lp', type: 'address' },
            { indexed: false, internalType: 'string', name: 'name', type: 'string' },
            { indexed: false, internalType: 'string', name: 'symbol', type: 'string' },
            { indexed: false, internalType: 'string', name: 'description', type: 'string' },
            { indexed: false, internalType: 'string', name: 'image', type: 'string' },
            { indexed: false, internalType: 'uint256', name: 'initialSupply', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'maxSupply', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'initialETHReserves', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'initialPrice', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'initialMarketCap', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'targetETH', type: 'uint256' },
        ],
        name: 'GuCoinDeployed',
        type: 'event',
    },
    { anonymous: false, inputs: [{ indexed: false, internalType: 'address', name: 'liquidityManager', type: 'address' }], name: 'GuLiquidityManagerUpdated', type: 'event' },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
            { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
        ],
        name: 'OwnershipTransferred',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: false, internalType: 'address', name: 'oldHarvester', type: 'address' },
            { indexed: false, internalType: 'address', name: 'newHarvester', type: 'address' },
        ],
        name: 'UpdatedHarvester',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: false, internalType: 'uint256', name: 'virtualReserves', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'initialSupply', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'maxSupply', type: 'uint256' },
        ],
        name: 'UpdatedInitialParams',
        type: 'event',
    },
    { inputs: [], name: 'LAYERZERO_ENDPOINT', outputs: [{ internalType: 'address', name: '', type: 'address' }], stateMutability: 'view', type: 'function' },
    { inputs: [], name: 'MAX_FEE', outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
    { inputs: [], name: 'POSITION_MANAGER', outputs: [{ internalType: 'address', name: '', type: 'address' }], stateMutability: 'view', type: 'function' },
    { inputs: [], name: 'PROTOCOL_PAUSED', outputs: [{ internalType: 'bool', name: '', type: 'bool' }], stateMutability: 'view', type: 'function' },
    { inputs: [], name: 'WETH', outputs: [{ internalType: 'address', name: '', type: 'address' }], stateMutability: 'view', type: 'function' },
    { inputs: [], name: 'bondingCurve', outputs: [{ internalType: 'contract IGuBondingCurve', name: '', type: 'address' }], stateMutability: 'view', type: 'function' },
    {
        inputs: [
            { internalType: 'string', name: 'name', type: 'string' },
            { internalType: 'string', name: 'symbol', type: 'string' },
            { internalType: 'string', name: 'description', type: 'string' },
            { internalType: 'string', name: 'image', type: 'string' },
        ],
        name: 'deploy',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'payable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: '', type: 'address' }],
        name: 'gucoins',
        outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
        name: 'gucoinsParams',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    { inputs: [], name: 'harvester', outputs: [{ internalType: 'address', name: '', type: 'address' }], stateMutability: 'view', type: 'function' },
    { inputs: [], name: 'liquidityManager', outputs: [{ internalType: 'address', name: '', type: 'address' }], stateMutability: 'view', type: 'function' },
    { inputs: [], name: 'maxSupply', outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
    { inputs: [], name: 'owner', outputs: [{ internalType: 'address', name: '', type: 'address' }], stateMutability: 'view', type: 'function' },
    { inputs: [], name: 'renounceOwnership', outputs: [], stateMutability: 'nonpayable', type: 'function' },
    { inputs: [{ internalType: 'address', name: '_bondingCurve', type: 'address' }], name: 'setBondingCurve', outputs: [], stateMutability: 'nonpayable', type: 'function' },
    { inputs: [{ internalType: 'address', name: '_harvester', type: 'address' }], name: 'setHarvester', outputs: [], stateMutability: 'nonpayable', type: 'function' },
    {
        inputs: [{ internalType: 'address', name: '_liquidityManager', type: 'address' }],
        name: 'setLiquidityManager',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    { inputs: [{ internalType: 'bool', name: '_state', type: 'bool' }], name: 'setProtocolPaused', outputs: [], stateMutability: 'nonpayable', type: 'function' },
    { inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }], name: 'transferOwnership', outputs: [], stateMutability: 'nonpayable', type: 'function' },
    {
        inputs: [
            { internalType: 'uint80', name: '_protocolFee', type: 'uint80' },
            { internalType: 'uint80', name: '_creatorFee', type: 'uint80' },
            { internalType: 'uint80', name: '_creationFee', type: 'uint80' },
        ],
        name: 'updateFees',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'uint256', name: '_virtualReserves', type: 'uint256' },
            { internalType: 'uint256', name: '_initialSupply', type: 'uint256' },
            { internalType: 'uint256', name: '_maxSupply', type: 'uint256' },
        ],
        name: 'updateInitialParams',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    { inputs: [{ internalType: 'uint256', name: 'amount', type: 'uint256' }], name: 'withdraw', outputs: [], stateMutability: 'nonpayable', type: 'function' },
];